name: Test workflow

on: #instruction que l'on envoit au github action
  push: 

jobs: #on peut appler nos jobs comme on veut
  echo-test: 
    runs-on: ubuntu-latest #défini sur quelle plateforme on lance le test

    steps: # on récupère les dépendances sur le github marketplace
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    #on met des -name pour nommer nos actions et donner des indications sur ce que font nos commandes
    - name: Install dependencies 
      - run: npm ci

    - name : Run unit tests
      - run: npm test

    
    - name: Echo the name
      run: | #le pipe est là pour pouvoir ecrire toute nos instructions les unes en dessous des autres
        export NAME=$Barbozii
        echo the $NAME
